fos_rest:
    body_listener:
        enabled: true
        default_format: json
    param_fetcher_listener:
        enabled: true
        force: true
    view:
        view_response_listener:
            enabled: true
    format_listener:
        rules:
            - { path: ^/api, prefer_extension: true, fallback_format: json, priorities: [ json ] }
    exception:
        codes: 
            'App\Exception\ErrorException': 400
